language: node_js
branches:
  only:
    - master
deploy:
  edge: true
  provider: cloudfoundry
  api: $CF_API
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: $CF_ORG
  space: $CF_SPACE
node_js:
  - "0.10.35"
notifications:
  email:
    recipients:
      - extrememoderationtv@gmail.com
services: mongodb
